import type { AllParameters } from '../types/index.js';
import { DEFAULT_PRESET } from '../audio/presets';
import { DEFAULT_ECOLOGY_CONFIG } from '../engine/SpeciesConfigs';

// Default Performance Parameters (defined locally to avoid circular dependency)
const defaultPerformanceParams = {
  autoOptimize: true,
  targetFPS: 60,
  qualityPreset: 'high' as const,
  _currentOptLevel: 0,
};

/**
 * MASTER PRESETS
 *
 * Complete "Experiences" that combine ALL parameters across all tabs
 * for stunning visual effects that showcase the full potential of the app.
 *
 * Each preset is a complete AllParameters object with:
 * - Physics (decay, diffusion, trails)
 * - Species behavior (sensors, movement)
 * - Temporal (speed, agent count)
 * - Visuals (colors, blend modes)
 * - Effects (bloom, kaleidoscope, feedback, etc.)
 */

export interface MasterPreset {
  name: string;
  icon: string;
  description: string;
  params: AllParameters;
}

export const masterPresets: MasterPreset[] = [
  {
    name: 'Cosmic Meditation',
    icon: '🌌',
    description: 'Slow, hypnotic mandala with deep space colors and gentle bloom',
    params: {
      universal: {
        physical: {
          decayRate: 0.97,
          diffusionFreq: 3,
          fadeStrength: 0.10,
          trailSaturation: 255,
        },
        semiotic: {
          sensorDist: 30,
          sensorAngle: 0.5,
          deposit: 20,
          turnSpeed: 0.3,
        },
        temporal: {
          speed: 0.8,
          chaosInterval: 0,
          chaosStrength: 0,
        },
        resonance: {
          attractionStrength: 1.0,
          repulsionStrength: -0.2,
          crossSpeciesInteraction: true,
          interactionMatrix: {
            redToRed: 0.5, redToGreen: 0.0, redToBlue: 0.0,
            greenToRed: 0.0, greenToGreen: 0.5, greenToBlue: 0.0,
            blueToRed: 0.0, blueToGreen: 0.0, blueToBlue: 0.5,
          },
        },
        audio: DEFAULT_PRESET,
      },
      species: {
        red: { physical: {}, semiotic: {}, temporal: {}, resonance: {}, audio: {} },
        green: { physical: {}, semiotic: {}, temporal: {}, resonance: {}, audio: {} },
        blue: { physical: {}, semiotic: {}, temporal: {}, resonance: {}, audio: {} },
      },
      globalTemporal: {
        agentCount: 1800,
        simulationSpeed: 1.0,
      },
      visualization: {
        brightness: 3.0,
        blendMode: 'additive',
        trailIntensity: 180,
        colorRed: { r: 255, g: 0, b: 200 },      // Magenta
        colorGreen: { r: 120, g: 100, b: 255 },  // Purple
        colorBlue: { r: 255, g: 150, b: 255 },   // Pink
        colorBg: { r: 2, g: 0, b: 8 },
        showAgents: true,
        useTriangles: true,
        hueCycling: {
          enabled: false,
          startHue: 0,
          endHue: 360,
          speed: 1.0,
        },
      },
      effects: {
        blur: 2,
        bloom: 0,
        bloomThreshold: 0.6,
        bloomRadius: 6,
        bloomIntensity: 1.2,
        saturation: 1.3,
        contrast: 1.05,
        hueShift: 0,
        motionBlur: 0.25,
        vignette: 0.3,
        chromaticAberration: 0,
        waveDistortion: 0,
        scanlines: 0,
        pixelation: 1,
        feedbackAmount: 0,
        feedbackZoom: 1.0,
        feedbackRotation: 0,
        feedbackOffsetX: 0,
        feedbackOffsetY: 0,
        kaleidoscopeSegments: 8,
        kaleidoscopeRotation: 0,
        kaleidoscopeZoom: 1.0,
        radialBlurStrength: 0,
        radialBlurCenterX: 0.5,
        radialBlurCenterY: 0.5,
        radialBlurQuality: 6,
        displacementStrength: 0,
        displacementScale: 1.5,
        displacementTime: 0,
        displacementAngle: 0,
        colorLUT: 'none',
        colorLUTIntensity: 1.0,
        mirrorMode: 'none',
        mirrorPosition: 0.5,
      },
      performance: defaultPerformanceParams,
      modelParams: {
        model: 'M1',
        m2: { highThreshold: 120, lowThreshold: 30, explorationNoise: 0.3 },
        m3: { phaseRotationRate: 0.005, amplitudeCoupling: 0.15, contextThreshold: 250, phaseNoise: 0.05 },
      },
      ecosystemMode: false,
      ecosystem: DEFAULT_ECOLOGY_CONFIG,
    },
  },

  {
    name: 'Liquid Rainbow',
    icon: '🌈',
    description: 'Fluid, colorful chaos with hue cycling and high diffusion',
    params: {
      universal: {
        physical: {
          decayRate: 0.92,
          diffusionFreq: 2,
          fadeStrength: 0.12,
          trailSaturation: 220,
        },
        semiotic: {
          sensorDist: 25,
          sensorAngle: 0.8,
          deposit: 15,
          turnSpeed: 0.8,
        },
        temporal: {
          speed: 1.5,
          chaosInterval: 120,
          chaosStrength: 0.8,
        },
        resonance: {
          attractionStrength: 1.1,
          repulsionStrength: -0.3,
          crossSpeciesInteraction: true,
          interactionMatrix: {
            redToRed: 0.5, redToGreen: 0.0, redToBlue: 0.0,
            greenToRed: 0.0, greenToGreen: 0.5, greenToBlue: 0.0,
            blueToRed: 0.0, blueToGreen: 0.0, blueToBlue: 0.5,
          },
        },
        audio: DEFAULT_PRESET,
      },
      species: {
        red: { physical: {}, semiotic: {}, temporal: {}, resonance: {}, audio: {} },
        green: { physical: {}, semiotic: {}, temporal: {}, resonance: {}, audio: {} },
        blue: { physical: {}, semiotic: {}, temporal: {}, resonance: {}, audio: {} },
      },
      globalTemporal: {
        agentCount: 2200,
        simulationSpeed: 1.0,
      },
      visualization: {
        brightness: 4.2,
        blendMode: 'screen',
        trailIntensity: 130,
        colorRed: { r: 255, g: 50, b: 150 },
        colorGreen: { r: 50, g: 255, b: 255 },
        colorBlue: { r: 255, g: 255, b: 50 },
        colorBg: { r: 5, g: 5, b: 15 },
        showAgents: false,  // Pure trails for liquid effect
        useTriangles: true,
        hueCycling: {
          enabled: true,
          startHue: 0,
          endHue: 360,
          speed: 2.5,
        },
      },
      effects: {
        blur: 4,
        bloom: 0,
        bloomThreshold: 0.5,
        bloomRadius: 7,
        bloomIntensity: 1.4,
        saturation: 1.8,
        contrast: 1.15,
        hueShift: 0,
        motionBlur: 0.5,
        vignette: 0.15,
        chromaticAberration: 0,
        waveDistortion: 0,
        scanlines: 0,
        pixelation: 1,
        feedbackAmount: 0,
        feedbackZoom: 1.0,
        feedbackRotation: 0,
        feedbackOffsetX: 0,
        feedbackOffsetY: 0,
        kaleidoscopeSegments: 0,
        kaleidoscopeRotation: 0,
        kaleidoscopeZoom: 1.0,
        radialBlurStrength: 0,
        radialBlurCenterX: 0.5,
        radialBlurCenterY: 0.5,
        radialBlurQuality: 6,
        displacementStrength: 0,
        displacementScale: 1.5,
        displacementTime: 0,
        displacementAngle: 0,
        colorLUT: 'none',
        colorLUTIntensity: 1.0,
        mirrorMode: 'none',
        mirrorPosition: 0.5,
      },
      performance: defaultPerformanceParams,
      modelParams: {
        model: 'M1',
        m2: { highThreshold: 120, lowThreshold: 30, explorationNoise: 0.3 },
        m3: { phaseRotationRate: 0.005, amplitudeCoupling: 0.15, contextThreshold: 250, phaseNoise: 0.05 },
      },
      ecosystemMode: false,
      ecosystem: DEFAULT_ECOLOGY_CONFIG,
    },
  },

  {
    name: 'Infinite Tunnel',
    icon: '🌀',
    description: 'Recursive feedback zoom with radial blur - warp speed effect',
    params: {
      universal: {
        physical: {
          decayRate: 0.95,
          diffusionFreq: 3,
          fadeStrength: 0.10,
          trailSaturation: 240,
        },
        semiotic: {
          sensorDist: 35,
          sensorAngle: 0.6,
          deposit: 12,
          turnSpeed: 0.6,
        },
        temporal: {
          speed: 2.0,
          chaosInterval: 0,
          chaosStrength: 0,
        },
        resonance: {
          attractionStrength: 1.0,
          repulsionStrength: -0.2,
          crossSpeciesInteraction: true,
          interactionMatrix: {
            redToRed: 0.5, redToGreen: 0.0, redToBlue: 0.0,
            greenToRed: 0.0, greenToGreen: 0.5, greenToBlue: 0.0,
            blueToRed: 0.0, blueToGreen: 0.0, blueToBlue: 0.5,
          },
        },
        audio: DEFAULT_PRESET,
      },
      species: {
        red: { physical: {}, semiotic: {}, temporal: {}, resonance: {}, audio: {} },
        green: { physical: {}, semiotic: {}, temporal: {}, resonance: {}, audio: {} },
        blue: { physical: {}, semiotic: {}, temporal: {}, resonance: {}, audio: {} },
      },
      globalTemporal: {
        agentCount: 2000,
        simulationSpeed: 1.0,
      },
      visualization: {
        brightness: 3.5,
        blendMode: 'additive',
        trailIntensity: 140,
        colorRed: { r: 255, g: 0, b: 100 },
        colorGreen: { r: 0, g: 255, b: 150 },
        colorBlue: { r: 100, g: 200, b: 255 },
        colorBg: { r: 0, g: 0, b: 0 },
        showAgents: false,
        useTriangles: true,
        hueCycling: {
          enabled: false,
          startHue: 0,
          endHue: 360,
          speed: 1.0,
        },
      },
      effects: {
        blur: 2,
        bloom: 0,
        bloomThreshold: 0.5,
        bloomRadius: 8,
        bloomIntensity: 1.5,
        saturation: 1.4,
        contrast: 1.25,
        hueShift: 0,
        motionBlur: 0.2,
        vignette: 0.5,
        chromaticAberration: 3,
        waveDistortion: 0,
        scanlines: 0,
        pixelation: 1,
        feedbackAmount: 0.88,
        feedbackZoom: 1.006,
        feedbackRotation: 0,
        feedbackOffsetX: 0,
        feedbackOffsetY: 0,
        kaleidoscopeSegments: 0,
        kaleidoscopeRotation: 0,
        kaleidoscopeZoom: 1.0,
        radialBlurStrength: 0.6,
        radialBlurCenterX: 0.5,
        radialBlurCenterY: 0.5,
        radialBlurQuality: 8,
        displacementStrength: 0,
        displacementScale: 1.5,
        displacementTime: 0,
        displacementAngle: 0,
        colorLUT: 'none',
        colorLUTIntensity: 1.0,
        mirrorMode: 'none',
        mirrorPosition: 0.5,
      },
      performance: defaultPerformanceParams,
      modelParams: {
        model: 'M1',
        m2: { highThreshold: 120, lowThreshold: 30, explorationNoise: 0.3 },
        m3: { phaseRotationRate: 0.005, amplitudeCoupling: 0.15, contextThreshold: 250, phaseNoise: 0.05 },
      },
      ecosystemMode: false,
      ecosystem: DEFAULT_ECOLOGY_CONFIG,
    },
  },

  {
    name: 'Crystal Palace',
    icon: '💎',
    description: 'Crystalline trails with 12-way mandala and mirror symmetry',
    params: {
      universal: {
        physical: {
          decayRate: 0.98,
          diffusionFreq: 8,
          fadeStrength: 0.08,
          trailSaturation: 255,
        },
        semiotic: {
          sensorDist: 20,
          sensorAngle: 0.4,
          deposit: 25,
          turnSpeed: 0.25,
        },
        temporal: {
          speed: 1.0,
          chaosInterval: 0,
          chaosStrength: 0,
        },
        resonance: {
          attractionStrength: 1.2,
          repulsionStrength: -0.1,
          crossSpeciesInteraction: true,
          interactionMatrix: {
            redToRed: 0.5, redToGreen: 0.0, redToBlue: 0.0,
            greenToRed: 0.0, greenToGreen: 0.5, greenToBlue: 0.0,
            blueToRed: 0.0, blueToGreen: 0.0, blueToBlue: 0.5,
          },
        },
        audio: DEFAULT_PRESET,
      },
      species: {
        red: { physical: {}, semiotic: {}, temporal: {}, resonance: {}, audio: {} },
        green: { physical: {}, semiotic: {}, temporal: {}, resonance: {}, audio: {} },
        blue: { physical: {}, semiotic: {}, temporal: {}, resonance: {}, audio: {} },
      },
      globalTemporal: {
        agentCount: 2400,
        simulationSpeed: 1.0,
      },
      visualization: {
        brightness: 4.0,
        blendMode: 'additive',
        trailIntensity: 100,
        colorRed: { r: 200, g: 220, b: 255 },    // Ice Blue
        colorGreen: { r: 220, g: 255, b: 240 },  // Mint
        colorBlue: { r: 230, g: 240, b: 255 },   // Crystal White
        colorBg: { r: 5, g: 5, b: 15 },
        showAgents: true,
        useTriangles: false,  // Dots for crystal points
        hueCycling: {
          enabled: false,
          startHue: 0,
          endHue: 360,
          speed: 1.0,
        },
      },
      effects: {
        blur: 1,
        bloom: 0,
        bloomThreshold: 0.7,
        bloomRadius: 5,
        bloomIntensity: 1.3,
        saturation: 1.1,
        contrast: 1.3,
        hueShift: 0,
        motionBlur: 0.1,
        vignette: 0.2,
        chromaticAberration: 0,
        waveDistortion: 0,
        scanlines: 0,
        pixelation: 1,
        feedbackAmount: 0,
        feedbackZoom: 1.0,
        feedbackRotation: 0,
        feedbackOffsetX: 0,
        feedbackOffsetY: 0,
        kaleidoscopeSegments: 12,
        kaleidoscopeRotation: 15,
        kaleidoscopeZoom: 1.0,
        radialBlurStrength: 0,
        radialBlurCenterX: 0.5,
        radialBlurCenterY: 0.5,
        radialBlurQuality: 6,
        displacementStrength: 0,
        displacementScale: 1.5,
        displacementTime: 0,
        displacementAngle: 0,
        colorLUT: 'none',
        colorLUTIntensity: 1.0,
        mirrorMode: 'quad',
        mirrorPosition: 0.5,
      },
      performance: defaultPerformanceParams,
      modelParams: {
        model: 'M1',
        m2: { highThreshold: 120, lowThreshold: 30, explorationNoise: 0.3 },
        m3: { phaseRotationRate: 0.005, amplitudeCoupling: 0.15, contextThreshold: 250, phaseNoise: 0.05 },
      },
      ecosystemMode: false,
      ecosystem: DEFAULT_ECOLOGY_CONFIG,
    },
  },

  {
    name: 'Electric Storm',
    icon: '⚡',
    description: 'Chaotic energy with lightning-fast agents and chromatic aberration',
    params: {
      universal: {
        physical: {
          decayRate: 0.90,
          diffusionFreq: 2,
          fadeStrength: 0.20,
          trailSaturation: 180,
        },
        semiotic: {
          sensorDist: 50,
          sensorAngle: 1.2,
          deposit: 10,
          turnSpeed: 1.8,
        },
        temporal: {
          speed: 4.5,
          chaosInterval: 60,
          chaosStrength: 1.5,
        },
        resonance: {
          attractionStrength: 0.8,
          repulsionStrength: -0.5,
          crossSpeciesInteraction: true,
          interactionMatrix: {
            redToRed: 0.5, redToGreen: 0.0, redToBlue: 0.0,
            greenToRed: 0.0, greenToGreen: 0.5, greenToBlue: 0.0,
            blueToRed: 0.0, blueToGreen: 0.0, blueToBlue: 0.5,
          },
        },
        audio: DEFAULT_PRESET,
      },
      species: {
        red: { physical: {}, semiotic: {}, temporal: {}, resonance: {}, audio: {} },
        green: { physical: {}, semiotic: {}, temporal: {}, resonance: {}, audio: {} },
        blue: { physical: {}, semiotic: {}, temporal: {}, resonance: {}, audio: {} },
      },
      globalTemporal: {
        agentCount: 2400,
        simulationSpeed: 1.0,
      },
      visualization: {
        brightness: 5.0,
        blendMode: 'screen',
        trailIntensity: 90,
        colorRed: { r: 255, g: 255, b: 0 },      // Electric Yellow
        colorGreen: { r: 0, g: 255, b: 255 },    // Cyan
        colorBlue: { r: 255, g: 0, b: 255 },     // Magenta
        colorBg: { r: 0, g: 0, b: 5 },
        showAgents: true,
        useTriangles: true,
        hueCycling: {
          enabled: false,
          startHue: 0,
          endHue: 360,
          speed: 1.0,
        },
      },
      effects: {
        blur: 0,
        bloom: 0,
        bloomThreshold: 0.4,
        bloomRadius: 8,
        bloomIntensity: 1.8,
        saturation: 2.5,
        contrast: 1.5,
        hueShift: 0,
        motionBlur: 0.15,
        vignette: 0.4,
        chromaticAberration: 8,
        waveDistortion: 0,
        scanlines: 0.5,
        pixelation: 1,
        feedbackAmount: 0,
        feedbackZoom: 1.0,
        feedbackRotation: 0,
        feedbackOffsetX: 0,
        feedbackOffsetY: 0,
        kaleidoscopeSegments: 4,
        kaleidoscopeRotation: 45,
        kaleidoscopeZoom: 1.0,
        radialBlurStrength: 0,
        radialBlurCenterX: 0.5,
        radialBlurCenterY: 0.5,
        radialBlurQuality: 6,
        displacementStrength: 0,
        displacementScale: 1.5,
        displacementTime: 0,
        displacementAngle: 0,
        colorLUT: 'none',
        colorLUTIntensity: 1.0,
        mirrorMode: 'none',
        mirrorPosition: 0.5,
      },
      performance: defaultPerformanceParams,
      modelParams: {
        model: 'M1',
        m2: { highThreshold: 120, lowThreshold: 30, explorationNoise: 0.3 },
        m3: { phaseRotationRate: 0.005, amplitudeCoupling: 0.15, contextThreshold: 250, phaseNoise: 0.05 },
      },
      ecosystemMode: false,
      ecosystem: DEFAULT_ECOLOGY_CONFIG,
    },
  },

  {
    name: 'Deep Ocean',
    icon: '🌊',
    description: 'Fluid underwater motion with deep blues and gentle movement',
    params: {
      universal: {
        physical: {
          decayRate: 0.93,
          diffusionFreq: 2,
          fadeStrength: 0.15,
          trailSaturation: 230,
        },
        semiotic: {
          sensorDist: 18,
          sensorAngle: 0.6,
          deposit: 22,
          turnSpeed: 0.4,
        },
        temporal: {
          speed: 0.7,
          chaosInterval: 0,
          chaosStrength: 0,
        },
        resonance: {
          attractionStrength: 1.1,
          repulsionStrength: -0.2,
          crossSpeciesInteraction: true,
          interactionMatrix: {
            redToRed: 0.5, redToGreen: 0.0, redToBlue: 0.0,
            greenToRed: 0.0, greenToGreen: 0.5, greenToBlue: 0.0,
            blueToRed: 0.0, blueToGreen: 0.0, blueToBlue: 0.5,
          },
        },
        audio: DEFAULT_PRESET,
      },
      species: {
        red: { physical: {}, semiotic: {}, temporal: {}, resonance: {}, audio: {} },
        green: { physical: {}, semiotic: {}, temporal: {}, resonance: {}, audio: {} },
        blue: { physical: {}, semiotic: {}, temporal: {}, resonance: {}, audio: {} },
      },
      globalTemporal: {
        agentCount: 1600,
        simulationSpeed: 1.0,
      },
      visualization: {
        brightness: 2.5,
        blendMode: 'additive',
        trailIntensity: 200,
        colorRed: { r: 0, g: 100, b: 180 },      // Deep Blue
        colorGreen: { r: 0, g: 200, b: 200 },    // Turquoise
        colorBlue: { r: 20, g: 120, b: 220 },    // Ocean Blue
        colorBg: { r: 0, g: 2, b: 10 },
        showAgents: false,
        useTriangles: true,
        hueCycling: {
          enabled: false,
          startHue: 0,
          endHue: 360,
          speed: 1.0,
        },
      },
      effects: {
        blur: 6,
        bloom: 0,
        bloomThreshold: 0.7,
        bloomRadius: 6,
        bloomIntensity: 0.8,
        saturation: 1.2,
        contrast: 0.9,
        hueShift: 0,
        motionBlur: 0.6,
        vignette: 0.35,
        chromaticAberration: 0,
        waveDistortion: 0,
        scanlines: 0,
        pixelation: 1,
        feedbackAmount: 0,
        feedbackZoom: 1.0,
        feedbackRotation: 0,
        feedbackOffsetX: 0,
        feedbackOffsetY: 0,
        kaleidoscopeSegments: 0,
        kaleidoscopeRotation: 0,
        kaleidoscopeZoom: 1.0,
        radialBlurStrength: 0,
        radialBlurCenterX: 0.5,
        radialBlurCenterY: 0.5,
        radialBlurQuality: 6,
        displacementStrength: 0,
        displacementScale: 1.5,
        displacementTime: 0,
        displacementAngle: 0,
        colorLUT: 'none',
        colorLUTIntensity: 1.0,
        mirrorMode: 'horizontal',
        mirrorPosition: 0.5,
      },
      performance: defaultPerformanceParams,
      modelParams: {
        model: 'M1',
        m2: { highThreshold: 120, lowThreshold: 30, explorationNoise: 0.3 },
        m3: { phaseRotationRate: 0.005, amplitudeCoupling: 0.15, contextThreshold: 250, phaseNoise: 0.05 },
      },
      ecosystemMode: false,
      ecosystem: DEFAULT_ECOLOGY_CONFIG,
    },
  },

  {
    name: 'Sacred Geometry',
    icon: '🕉️',
    description: 'Recursive mandala with feedback and rotating kaleidoscope',
    params: {
      universal: {
        physical: {
          decayRate: 0.96,
          diffusionFreq: 3,
          fadeStrength: 0.12,
          trailSaturation: 245,
        },
        semiotic: {
          sensorDist: 28,
          sensorAngle: 0.5,
          deposit: 18,
          turnSpeed: 0.5,
        },
        temporal: {
          speed: 1.2,
          chaosInterval: 0,
          chaosStrength: 0,
        },
        resonance: {
          attractionStrength: 1.0,
          repulsionStrength: -0.15,
          crossSpeciesInteraction: true,
          interactionMatrix: {
            redToRed: 0.5, redToGreen: 0.0, redToBlue: 0.0,
            greenToRed: 0.0, greenToGreen: 0.5, greenToBlue: 0.0,
            blueToRed: 0.0, blueToGreen: 0.0, blueToBlue: 0.5,
          },
        },
        audio: DEFAULT_PRESET,
      },
      species: {
        red: { physical: {}, semiotic: {}, temporal: {}, resonance: {}, audio: {} },
        green: { physical: {}, semiotic: {}, temporal: {}, resonance: {}, audio: {} },
        blue: { physical: {}, semiotic: {}, temporal: {}, resonance: {}, audio: {} },
      },
      globalTemporal: {
        agentCount: 2000,
        simulationSpeed: 1.0,
      },
      visualization: {
        brightness: 3.5,
        blendMode: 'additive',
        trailIntensity: 160,
        colorRed: { r: 255, g: 100, b: 50 },     // Orange
        colorGreen: { r: 50, g: 255, b: 150 },   // Green
        colorBlue: { r: 150, g: 50, b: 255 },    // Purple
        colorBg: { r: 5, g: 5, b: 10 },
        showAgents: true,
        useTriangles: false,
        hueCycling: {
          enabled: true,
          startHue: 0,
          endHue: 360,
          speed: 1.5,
        },
      },
      effects: {
        blur: 1,
        bloom: 0,
        bloomThreshold: 0.6,
        bloomRadius: 5,
        bloomIntensity: 1.2,
        saturation: 1.6,
        contrast: 1.1,
        hueShift: 0,
        motionBlur: 0.1,
        vignette: 0.2,
        chromaticAberration: 0,
        waveDistortion: 0,
        scanlines: 0,
        pixelation: 1,
        feedbackAmount: 0.90,
        feedbackZoom: 1.0,
        feedbackRotation: 0.3,
        feedbackOffsetX: 0,
        feedbackOffsetY: 0,
        kaleidoscopeSegments: 12,
        kaleidoscopeRotation: 0,
        kaleidoscopeZoom: 1.0,
        radialBlurStrength: 0,
        radialBlurCenterX: 0.5,
        radialBlurCenterY: 0.5,
        radialBlurQuality: 6,
        displacementStrength: 0,
        displacementScale: 1.5,
        displacementTime: 0,
        displacementAngle: 0,
        colorLUT: 'none',
        colorLUTIntensity: 1.0,
        mirrorMode: 'none',
        mirrorPosition: 0.5,
      },
      performance: defaultPerformanceParams,
      modelParams: {
        model: 'M1',
        m2: { highThreshold: 120, lowThreshold: 30, explorationNoise: 0.3 },
        m3: { phaseRotationRate: 0.005, amplitudeCoupling: 0.15, contextThreshold: 250, phaseNoise: 0.05 },
      },
      ecosystemMode: false,
      ecosystem: DEFAULT_ECOLOGY_CONFIG,
    },
  },

  {
    name: 'Retro Arcade',
    icon: '👾',
    description: 'Pixelated retro gaming aesthetics with scanlines and vibrant colors',
    params: {
      universal: {
        physical: {
          decayRate: 0.95,
          diffusionFreq: 5,
          fadeStrength: 0.15,
          trailSaturation: 255,
        },
        semiotic: {
          sensorDist: 15,
          sensorAngle: 0.4,
          deposit: 30,
          turnSpeed: 0.6,
        },
        temporal: {
          speed: 2.5,
          chaosInterval: 0,
          chaosStrength: 0,
        },
        resonance: {
          attractionStrength: 1.3,
          repulsionStrength: -0.1,
          crossSpeciesInteraction: true,
          interactionMatrix: {
            redToRed: 0.5, redToGreen: 0.0, redToBlue: 0.0,
            greenToRed: 0.0, greenToGreen: 0.5, greenToBlue: 0.0,
            blueToRed: 0.0, blueToGreen: 0.0, blueToBlue: 0.5,
          },
        },
        audio: DEFAULT_PRESET,
      },
      species: {
        red: { physical: {}, semiotic: {}, temporal: {}, resonance: {}, audio: {} },
        green: { physical: {}, semiotic: {}, temporal: {}, resonance: {}, audio: {} },
        blue: { physical: {}, semiotic: {}, temporal: {}, resonance: {}, audio: {} },
      },
      globalTemporal: {
        agentCount: 1200,
        simulationSpeed: 1.0,
      },
      visualization: {
        brightness: 4.5,
        blendMode: 'additive',
        trailIntensity: 110,
        colorRed: { r: 255, g: 0, b: 100 },      // Hot Pink
        colorGreen: { r: 0, g: 255, b: 0 },      // Neon Green
        colorBlue: { r: 0, g: 150, b: 255 },     // Bright Blue
        colorBg: { r: 0, g: 0, b: 0 },
        showAgents: true,
        useTriangles: false,  // Dots for retro look
        hueCycling: {
          enabled: false,
          startHue: 0,
          endHue: 360,
          speed: 1.0,
        },
      },
      effects: {
        blur: 0,
        bloom: 0,
        bloomThreshold: 0.7,
        bloomRadius: 4,
        bloomIntensity: 0.8,
        saturation: 2.0,
        contrast: 1.4,
        hueShift: 0,
        motionBlur: 0.3,
        vignette: 0.3,
        chromaticAberration: 5,
        waveDistortion: 0,
        scanlines: 0.7,
        pixelation: 6,
        feedbackAmount: 0,
        feedbackZoom: 1.0,
        feedbackRotation: 0,
        feedbackOffsetX: 0,
        feedbackOffsetY: 0,
        kaleidoscopeSegments: 0,
        kaleidoscopeRotation: 0,
        kaleidoscopeZoom: 1.0,
        radialBlurStrength: 0,
        radialBlurCenterX: 0.5,
        radialBlurCenterY: 0.5,
        radialBlurQuality: 6,
        displacementStrength: 0,
        displacementScale: 1.5,
        displacementTime: 0,
        displacementAngle: 0,
        colorLUT: 'none',
        colorLUTIntensity: 1.0,
        mirrorMode: 'none',
        mirrorPosition: 0.5,
      },
      performance: defaultPerformanceParams,
      modelParams: {
        model: 'M1',
        m2: { highThreshold: 120, lowThreshold: 30, explorationNoise: 0.3 },
        m3: { phaseRotationRate: 0.005, amplitudeCoupling: 0.15, contextThreshold: 250, phaseNoise: 0.05 },
      },
      ecosystemMode: false,
      ecosystem: DEFAULT_ECOLOGY_CONFIG,
    },
  },
];
